export enum Permissions {
    VERIFY_COMMENTS = 'VERIFY_COMMENTS',
    VERIFY_BLOGS = 'VERIFY_BLOGS',
    POST_COMMENTS = 'POST_COMMENTS',
    POST_BLOGS = 'POST_BLOGS',
    DELETE_COMMENTS = 'DELETE_COMMENTS',
    DELETE_BLOGS = 'DELETE_BLOGS',
    UPDATE_COMMENTS = 'UPDATE_COMMENTS',
    UPDATE_BLOGS = 'UPDATE_BLOGS',
    ACCESS_ADMIN_PANEL = 'ACCESS_ADMIN_PANEL',
}