# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        service: [blog, comment]
    steps:
    - uses: actions/checkout@v3
      name: Use Node.js ${{ matrix.node-version }}
    - name: install dependencies
      run: npm --prefix ${{ matrix.service }} install
    - name: run tests
      run: npm --prefix ${{ matrix.service }} test
